### ISSUE TITLE
Assignment allowed for std::mutex and then crashes

### ISSUE THREAD

**Issue by OldWolf2** [meganz/mingw-std-threads#11]
This code compiles without error: 

    #include <mutex>
    struct S { std::mutex a; };

    int main()
    {
      S s, t;
        s = t;
    }

and sometimes crashes at runtime with access violation because DeleteCriticalSection is called twice on the same critical section. 

The same code fails to compile in a unix-based installation of g++, saying that S has a deleted `operator=` because `std::mutex` has a deleted `operator=`.

As a workaround, I added `void operator=(_NonRecursiveMutex<B> const &) = delete;`  to mingw.mutex.h, just after the existing line `_NonRecursiveMutex (const _NonRecursiveMutex<B>&) = delete;`.  But I have not investigated as to whether other mutexes or sync objects had the same problem also.

**Comment by alxvasilev** [comment]
Please can you file a Merge Request, and we will merge it.

**Comment by alxvasilev** [comment]
Fixed, thanks again.
