### ISSUE TITLE
Inline functions

### ISSUE THREAD

**Issue by fys-clesch** [meganz/mingw-std-threads#5]
Wouldn't it be nicer to have the functions defined by `inline`? Otherwise, having multiple .cpp files that all include the same, say "mingw.thread.h", file, the one definition rule isn't obeyed.

**Comment by DJuego** [comment]
Yep! I have had to modify the library.

multiple definition of `std::this_thread::get_id()'
multiple definition of `std::this_thread::yield()

mingw.thread.h:

```cpp
   thread::id get_id() {return thread::id(GetCurrentThreadId());}
   void yield() {Sleep(0);}
```
to

```cpp
    inline thread::id get_id() {return thread::id(GetCurrentThreadId());}
    inline void yield() {Sleep(0);}
```

Thank you for this FANTASTIC contribution (mingw-std-threads), **meganz** . Thanks! Thanks!!

**Comment by graidl** [comment]
I entirely agree - also ran into these linking problems with multiple definitions and had to make these functions inline. This should be fixed, but otherwise, this implementation works excellently! Thanks!

**Comment by alxvasilev** [comment]
Fixed. Thanks for reporting.
