### ISSUE TITLE
Problem with mutex.h

### ISSUE THREAD

**Issue by Jamaika1** [meganz/mingw-std-threads#54]
I don't know how to describe it. I mean that some programs don't tolerate <windows.h> and thus are incompatible with some typedef functions of the HALF, FLOAT or some cann't tolerate at all. Is there any idea to bypass this problem?
Recently, I have a problem compiling a new codec VVC with WPP PARALLEISM functions.
https://vcgit.hhi.fraunhofer.de/jvet/VVCSoftware_VTM
msg(**(MsgLevel)** ERROR

**Comment by nmcclatchey** [comment]
Short answer: Maybe.

Long answer:
The Windows headers define many macros, which is undesired in C++ because they are unscoped. The library currently includes the entire `windows.h` header, which includes every such macro. With care, replacing `windows.h` with more specific headers (eg. `syncapi.h`) should be possible, but that may not completely avoid the undesirable macros.
Taking it a step further, it may be possible to eschew the Windows headers completely (solving the problem), but abandoning a supplier-provided API is generally considered to be unwise.

**Comment by Jamaika1** [comment]
Thanks for the answer
One more question:
Why can in the typedef specifier not be found at compilation?  The typedef don't have declaration specifiers in windows.h and don't write declaration even using will update Minimize Windows headers.
enum MsgLevel
{
  SILENT  = 0,
  ERROR   = 1,
  WARNING = 2,
  INFO    = 3,
  NOTICE  = 4,
  VERBOSE = 5,
  DETAILS = 6
}; 
msg((MsgLevel) ERROR

**Comment by Jamaika1** [comment]
I understand that such errors rather impossible to delete.
```
In file included from c:\msys920\x86_64-w64-mingw32\include\hdrlib\inc\Global.H:71,
                 from c:\msys920\x86_64-w64-mingw32\include\hdrlib\inc\distortionmetric.h:55,
                 from c:\msys920\x86_64-w64-mingw32\include\encoderlib\EncCfg.h:51,
                 from c:\msys920\x86_64-w64-mingw32\include\encoderlib\enclib.h:48,
                 from EncApp.h:44,
                 from encmain.cpp:43:
c:\msys920\x86_64-w64-mingw32\include\hdrlib\inc\TypeDefs.H:155:10: error: 'UINT' redeclared as different kind of entity
  155 |   UINT = 0,                           // Unsigned integer (32 bit) type
      |          ^
In file included from c:\msys920\x86_64-w64-mingw32\include\synchapi.h:10,
                 from c:\msys920\x86_64-w64-mingw32\include\commonlib\mingw.mutex.h:51,
                 from c:\msys920\x86_64-w64-mingw32\include\commonlib\Picture.h:55,
                 from c:\msys920\x86_64-w64-mingw32\include\commonlib\loopfilter.h:43,
                 from c:\msys920\x86_64-w64-mingw32\include\encoderlib\enclib.h:43,
                 from EncApp.h:44,
                 from encmain.cpp:43:
c:\msys920\x86_64-w64-mingw32\include\minwindef.h:159:24: note: previous declaration 'typedef unsigned int UINT'
  159 |   typedef unsigned int UINT;
      |                        ^~~~
In file included from c:\msys920\x86_64-w64-mingw32\include\hdrlib\inc\Global.H:71,
                 from c:\msys920\x86_64-w64-mingw32\include\hdrlib\inc\distortionmetric.h:55,
                 from c:\msys920\x86_64-w64-mingw32\include\encoderlib\EncCfg.h:51,
                 from c:\msys920\x86_64-w64-mingw32\include\encoderlib\enclib.h:48,
                 from EncApp.h:44,
                 from encmain.cpp:43:
c:\msys920\x86_64-w64-mingw32\include\hdrlib\inc\TypeDefs.H:157:11: error: 'FLOAT' redeclared as different kind of entity
  157 |   FLOAT = 2,                          // Floating point (single precision - 32 bits)
      |           ^
In file included from c:\msys920\x86_64-w64-mingw32\include\synchapi.h:10,
                 from c:\msys920\x86_64-w64-mingw32\include\commonlib\mingw.mutex.h:51,
                 from c:\msys920\x86_64-w64-mingw32\include\commonlib\Picture.h:55,
                 from c:\msys920\x86_64-w64-mingw32\include\commonlib\loopfilter.h:43,
                 from c:\msys920\x86_64-w64-mingw32\include\encoderlib\enclib.h:43,
                 from EncApp.h:44,
                 from encmain.cpp:43:
c:\msys920\x86_64-w64-mingw32\include\minwindef.h:142:17: note: previous declaration 'typedef float FLOAT'
  142 |   typedef float FLOAT;
      |                 ^~~~~
```

**Comment by Jamaika1** [comment]
I don't know if I did the right thing. I replaced the lines in EncAppCfg.h and now the problem has disappeared. Until next time.

#include "CommonLib/CommonDef.h"

> #if JVET_O0756_CALCULATE_HDRMETRICS
> #include "HDRLib/inc/DistortionMetric.H"
> #endif

#include "EncoderLib/EncCfg.h"
#if EXTENSION_360_VIDEO
#include "AppEncHelper360/TExt360AppEncCfg.h"
#endif

#include <sstream>
#include <vector>

**Comment by nmcclatchey** [comment]
Generally, avoiding naming conflicts is the right thing to do. Your approach is viable, as would be placing your enum in a namespace.

Generally, following the naming conventions from a style guide is good practice. It doesn't _completely_ isolate you from problems (eg. the Windows API uses macros to fake argument-dependent lookup in C), but it can massively reduce the rate at which you encounter such problems. For example, reserving `ALL_CAPS_NAMES` for preprocessor macros will avoid many problems with older APIs.
