### ISSUE TITLE
Releasing on Github 

### ISSUE THREAD

**Issue by theodelrieu** [meganz/mingw-std-threads#60]
Hello,

I would like to know if you are planning to release a fixed version of this library? It'd be easier to package using specific tags rather than commit hashes as version numbers.

**Comment by alxvasilev** [comment]
Hello,
Haven't thought about that. As it's mostly bug and standard compliance fixes, I guess we would mostly bump a patch-level version with each commit, which would somewhat defeat a standard semantic versioning scheme. Any thoughts on this @nmcclatchey?

**Comment by nmcclatchey** [comment]
@theodelrieu If you use only those features both specified by the C++ standard and implemented in your current commit, then it is safe to update the version of the library to the latest head (eg. pulling from master). That said...

@alxvasilev I think semantic versioning would add value to the library. Even if we were only to bump the patch version from this point onward, it would provide a sense of safety to users of the library, which can be vital for wider adoption. Moreover, we occasionally implement a new feature from the standard (which bumps the minor version), and have on extremely rare occasions changed how macros are interpreted (may bump the major version); full semantic versioning is not unreasonable.

With this in mind, I recommend tagging the current head as version v1.0.0, and following semantic versioning. When a version of the C++ standard becomes fully supported, we can also add a tag for it. (Currently, C++11 is still missing a couple of features)

**Comment by alxvasilev** [comment]
Ok, guys, we now have v1.0.0. Cheers to that :)
