### ISSUE TITLE
synchapi.h: No such file or directory

### ISSUE THREAD

**Issue by JosuGZ** [meganz/mingw-std-threads#63]
Hi, I'm getting a `synchapi.h: No such file or directory`  error while trying to use `<mingw.thread.h>` under Windows 10. This is the output from `gcc -v`:

```
gcc -v
Using built-in specs.
COLLECT_GCC=C:\Program Files (x86)\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/Program\ Files\ (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/../libexec/gcc/i686-w64-mingw32/8.1.0/lto-wrapper.exe
Target: i686-w64-mingw32
Configured with: ../../../src/gcc-8.1.0/configure --host=i686-w64-mingw32 --build=i686-w64-mingw32 --target=i686-w64-mingw32 --prefix=/mingw32 --with-sysroot=/c/mingw810/i686-810-posix-dwarf-rt_v6-rev0/mingw32 --enable-shared --enable-static --disable-multilib --enable-languages=c,c++,fortran,lto --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --disable-sjlj-exceptions --with-dwarf2 --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap
--disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=i686 --with-tune=generic --with-libiconv --with-system-zlib --with-gmp=/c/mingw810/prerequisites/i686-w64-mingw32-static --with-mpfr=/c/mingw810/prerequisites/i686-w64-mingw32-static --with-mpc=/c/mingw810/prerequisites/i686-w64-mingw32-static --with-isl=/c/mingw810/prerequisites/i686-w64-mingw32-static --with-pkgversion='i686-posix-dwarf-rev0, Built by MinGW-W64 project' --with-bugurl=https://sourceforge.net/projects/mingw-w64 CFLAGS='-O2 -pipe -fno-ident -I/c/mingw810/i686-810-posix-dwarf-rt_v6-rev0/mingw32/opt/include -I/c/mingw810/prerequisites/i686-zlib-static/include -I/c/mingw810/prerequisites/i686-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -fno-ident -I/c/mingw810/i686-810-posix-dwarf-rt_v6-rev0/mingw32/opt/include -I/c/mingw810/prerequisites/i686-zlib-static/include -I/c/mingw810/prerequisites/i686-w64-mingw32-static/include' CPPFLAGS=' -I/c/mingw810/i686-810-posix-dwarf-rt_v6-rev0/mingw32/opt/include -I/c/mingw810/prerequisites/i686-zlib-static/include -I/c/mingw810/prerequisites/i686-w64-mingw32-static/include' LDFLAGS='-pipe -fno-ident -L/c/mingw810/i686-810-posix-dwarf-rt_v6-rev0/mingw32/opt/lib -L/c/mingw810/prerequisites/i686-zlib-static/lib -L/c/mingw810/prerequisites/i686-w64-mingw32-static/lib -Wl,--large-address-aware'
Thread model: posix
gcc version 8.1.0 (i686-posix-dwarf-rev0, Built by MinGW-W64 project)
```

It also happens with another version of gcc:

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/6.3.0/lto-wrapper.exe
Target: mingw32
Configured with: ../src/gcc-6.3.0/configure --build=x86_64-pc-linux-gnu --host=mingw32 --target=mingw32 --with-gmp=/mingw --with-mpfr --with-mpc=/mingw --with-isl=/mingw --prefix=/mingw --disable-win32-registry --with-arch=i586 --with-tune=generic --enable-languages=c,c++,objc,obj-c++,fortran,ada --with-pkgversion='MinGW.org GCC-6.3.0-1' --enable-static --enable-shared --enable-threads --with-dwarf2 --disable-sjlj-exceptions --enable-version-specific-runtime-libs --with-libiconv-prefix=/mingw --with-libintl-prefix=/mingw --enable-libstdcxx-debug --enable-libgomp --disable-libvtv --enable-nls
Thread model: win32
gcc version 6.3.0 (MinGW.org GCC-6.3.0-1)
```

Thoughts?

**Comment by nmcclatchey** [comment]
[The header `synchapi.h` is a Windows header.](https://docs.microsoft.com/en-us/windows/win32/api/synchapi/) It is used directly by the library to avoid including `windows.h`, to avoid pulling in anything that can be avoided.

If it is not found, then this hints that part of the Windows API is missing in your configuration, or was not found by GCC's include path. This may be due to the version of MinGW that you are using. Please search the system header files for `windows.h`, and let us know if `synchapi.h` is in the same directory.

**Comment by JosuGZ** [comment]
I'm actually including `#include <Windows.h>` in my application as it is (currently) a WinAPI program, and it works (until I try to use threads). I'm not sure where that header comes from though, there are a bunch of include directories and some of them do contain the file.

**Comment by JosuGZ** [comment]
From my include path (`gcc -xc++ -E -v -`)

```
#include "..." search starts here:
#include <...> search starts here:
 C:/Program Files/mingw-w64/x86_64-8.1.0-win32-seh-rt_v6-rev0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++
 C:/Program Files/mingw-w64/x86_64-8.1.0-win32-seh-rt_v6-rev0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/x86_64-w64-mingw32
 C:/Program Files/mingw-w64/x86_64-8.1.0-win32-seh-rt_v6-rev0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/backward
 C:/Program Files/mingw-w64/x86_64-8.1.0-win32-seh-rt_v6-rev0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/include
 C:/Program Files/mingw-w64/x86_64-8.1.0-win32-seh-rt_v6-rev0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/include-fixed
 C:/Program Files/mingw-w64/x86_64-8.1.0-win32-seh-rt_v6-rev0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/include
End of search list.
```

This folder ` C:/Program Files/mingw-w64/x86_64-8.1.0-win32-seh-rt_v6-rev0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/include` does contain both files :S

![image](https://user-images.githubusercontent.com/25986871/68496851-8aa79100-0253-11ea-93c8-0c7650035f65.png)

**Comment by JosuGZ** [comment]
It seems like gcc was using the MinGW includes although I had MinGW w64 placed _before_ on my path, and MinGW includes "windows.h" but not "synchapi.h". Removing the good old MinGW from the path solves the issue, although now I'm getting a huge pile of warnings from some headers, but that is a different story.

Should MinGW be supported by this library? If not, this can be closed.

**Comment by nmcclatchey** [comment]
This, and a check of all files included by MinGW-w32, indicates that MinGW's version of the Windows API does not match Microsoft's documentation. However, it appears that [distinguishing between MinGW and MinGW-w64 is possible, using the macro `__MINGW64_VERSION_MAJOR`.](https://sourceforge.net/p/predef/wiki/Compilers/)

I'll put together a compatibility patch to include only `windows.h` (and warn about incompatibility) if MinGW-w32 is detected.

**Comment by nmcclatchey** [comment]
Correction:
I am not sure that this is feasible in MinGW-w32. The `process.h` file (which includes definitions not provided by `windows.h`) seems to be missing from MinGW-w32's include directory. I have put something together nonetheless.

The following revision makes a best-effort attempt to implement the library in MinGW-w32: [njmcclatchey/mingw-std-threads/MinGW-w32-compatibility](https://github.com/nmcclatchey/mingw-std-threads/tree/MinGW-w32-compatibility)

**Comment by JosuGZ** [comment]
It seems to work with a simple thread :)

**Comment by nmcclatchey** [comment]
PR #64 has been created to address this. Thank you for helping with testing.
