### ISSUE TITLE
The wait_for method of std::future is problem

### ISSUE THREAD

**Issue by phyyww** [meganz/mingw-std-threads#76]
The wait_for method of std::future cannot return over time, and the time parameter is invalid

**Comment by nmcclatchey** [comment]
Hi. I wrote the original implementation. Could you provide more detail about what's wrong with it?

Examination of the [method|https://github.com/meganz/mingw-std-threads/blob/c01463398bd2b09c2afa0cd06c12d7b1cc8a470d/mingw.future.h#L199] doesn't reveal any flaws that match your description.

**Comment by phyyww** [comment]
I am very glad to receive your reply. Maybe you can try to test it with the following code. The mingw I use is compiled and run on windows, and it will not output "timeout". Normally, it should print out "timeout", thank you!

``int test_shared_future_3()
{
	std::shared_future<int> fut = std::async(std::launch::async, [](){
        std::this_thread::sleep_for(std::chrono::seconds(5));
        return 8;
    });

    std::cout << "waiting...\n";
    std::future_status status;

    do {
        status = fut.wait_for(std::chrono::seconds(1));
        if (status == std::future_status::deferred) {
            std::cout << "deferred\n";
        } else if (status == std::future_status::timeout) {
            std::cout << "timeout\n";
        } else if (status == std::future_status::ready) {
            std::cout << "ready!\n";
        }
    } while (status != std::future_status::ready);

    std::cout << "result is " << fut.get() << '\n';

	return 0;
}

**Comment by nmcclatchey** [comment]
Thanks for the test case.

The issue has been identified: `async` is locking the same mutex used for sleeping when `wait_for` is called. This lock is held during the entire computation, which is not correct behavior. I'll put together a patch.

**Comment by nmcclatchey** [comment]
See #77

**Comment by phyyww** [comment]
thank you for your support

**Comment by alxvasilev** [comment]
Fix merged
