### ISSUE TITLE
Missing std::once_flag

### ISSUE THREAD

**Issue by karalabe** [meganz/mingw-std-threads#8]
I've tried incorporating your headers into a recent mingw build, and it works beautifully, but I noticed one missing construct that the upstream mutex header has (based on gthreads), but your implementation misses. It's the `std::once_flag`. Any pointers on how I could work around this issue (beside reworking the client code not to use it :P)? Thanks!

**Comment by dwbuiten** [comment]
It could be implemented in this project natively, using `InitOnceBeginInitialize` / `InitOnceComplete`, like this: https://git.libav.org/?p=libav.git;a=blob;f=compat/w32pthreads.h;h=2fe2a5ab979ff676d1e7dba4a360306dde29a0f0;hb=HEAD#l130

If for some reason you hate like and want XP support, then: https://git.libav.org/?p=libav.git;a=blob;f=compat/w32pthreads.h;h=2fe2a5ab979ff676d1e7dba4a360306dde29a0f0;hb=HEAD#l187

**Comment by alxvasilev** [comment]
Unfortunately this is outside the scope of this implementation, at least for now. However we will have it in mind if we decide to extend the scope of this implementation. Thanks you for reporting, your feedback and feature requests are appreciated.

**Comment by dwbuiten** [comment]
Any reason why it's out of scope (I don't see the scope written anywhere)?

I think `std::call_once` is one of the quintessential parts of `<mutex>`, in my opinion, and I am sure we are happy to contribute our implementation.

**Comment by yselkowitz** [comment]
I agree that this is needed.  @dwbuiten, if you provide a patch, it may have a better chance of being accepted.

**Comment by alxvasilev** [comment]
The scope was to provide the platform-specific code for implementing the basic primitive classes - thread, mutex, condvar. Most of the rest should be implementable on top of them. Of course, if you can provide a patch, we can merge it.
