### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by LB--** [meganz/mingw-std-threads#9]
I can't find a license anywhere, and this prevents me from using any of the code here. At the very least you should provide a LICENSE file. If you just want anyone to be able to use the code, then make it public domain via [unlicense](http://unlicense.org/).

**Comment by MT-Wizard** [comment]
+1 this. Could you please add some clarification about the license type of the code? I'd really like to use it

**Comment by alxvasilev** [comment]
The license will be simplified 2-clause BSD license. We removed it expecting the code to be merged in the official MINGW standard library, but this hasn't happened so far.

**Comment by alxvasilev** [comment]
License added. Thanks for using this code, and for your feedback.
